---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference upstream OLM dependencies (cert-manager, metallb, nmstate, coo)
components:
  - https://github.com/openstack-k8s-operators/architecture/lib/olm-deps?ref=main
  - https://github.com/openstack-k8s-operators/gitops/components/argocd/annotations?ref=main

# OpenStack operator (not included in olm-deps)
resources:
  - openstack-operator.yaml
