# OpenStack Operator CatalogSource and Subscription
---
apiVersion: v1
kind: Namespace
metadata:
  name: openstack-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: openstack-operator-index
  namespace: openstack-operators
spec:
  sourceType: grpc
  # RHOSO 18.0 operator index (internal Red Hat build)
  image: registry-proxy.engineering.redhat.com/rh-osbs/iib:1109519
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openstack
  namespace: openstack-operators
spec:
  targetNamespaces: []
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openstack-operator
  namespace: openstack-operators
spec:
  name: openstack-operator
  channel: stable-v1.0
  source: openstack-operator-index
  sourceNamespace: openstack-operators
